# Generated by Django 4.1.4 on 2024-10-04 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.BigIntegerField(max_length=100)),
                ('to_id', models.BigIntegerField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('experience', models.BigIntegerField(max_length=100)),
                ('certificate', models.FileField(upload_to='')),
                ('image', models.FileField(upload_to='')),
                ('licence', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='yoga_trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('experience', models.BigIntegerField(max_length=100)),
                ('certificate', models.FileField(upload_to='')),
                ('image', models.FileField(upload_to='')),
                ('licence', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='')),
                ('date', models.DateField(max_length=100)),
                ('descriptions', models.CharField(max_length=100)),
                ('TRAINER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.yoga_trainer')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='trainer_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('TRAINER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.yoga_trainer')),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.user')),
            ],
        ),
        migrations.CreateModel(
            name='tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=100)),
                ('descriptions', models.CharField(max_length=100)),
                ('TRAINER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.yoga_trainer')),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=100)),
                ('from_time', models.TimeField(max_length=100)),
                ('to_time', models.TimeField(max_length=100)),
                ('DOCTOR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.CharField(max_length=100)),
                ('BOOKING_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.booking')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.login_table'),
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=100)),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.user')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='SCHEDULE_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.schedule'),
        ),
        migrations.AddField(
            model_name='booking',
            name='USER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.user'),
        ),
    ]
