# Generated by Django 4.1.4 on 2024-10-18 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0003_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='DOCTOR_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MYAPP.doctor'),
            preserve_default=False,
        ),
    ]
