# Generated by Django 4.1.4 on 2024-10-25 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0005_remove_schedule_doctor_id_schedule_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='USER_ID',
        ),
        migrations.AddField(
            model_name='schedule',
            name='DOCTOR_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MYAPP.doctor'),
            preserve_default=False,
        ),
    ]
