# Generated by Django 4.1.4 on 2024-10-25 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0006_remove_schedule_user_id_schedule_doctor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='prescription_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pres', models.CharField(max_length=100)),
                ('BOOK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.booking')),
            ],
        ),
    ]
