# Generated by Django 4.1.4 on 2024-11-01 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0007_prescription_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tips',
            new_name='tips_table',
        ),
    ]
