# Generated by Django 4.1.4 on 2024-11-01 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0008_rename_tips_tips_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='from_id',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='message',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='to_id',
        ),
        migrations.AddField(
            model_name='chat',
            name='fromid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fromid', to='MYAPP.login_table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='msg',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='toid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='toid', to='MYAPP.login_table'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateField(),
        ),
    ]
