# Generated by Django 3.2.25 on 2024-11-02 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0010_doctor_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='LOGIN',
        ),
        migrations.AddField(
            model_name='review',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MYAPP.user'),
            preserve_default=False,
        ),
    ]
