# Generated by Django 3.2.25 on 2024-11-03 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0012_trainer_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer_review',
            name='rating',
        ),
    ]
