# Generated by Django 5.1.3 on 2024-11-15 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0013_remove_trainer_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='doc_complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('DOCTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.doctor')),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.user')),
            ],
        ),
        migrations.CreateModel(
            name='trainer_complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('TRAINER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.yoga_trainer')),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.user')),
            ],
        ),
        migrations.DeleteModel(
            name='complaint',
        ),
    ]
