# Generated by Django 5.1.3 on 2024-11-15 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0014_doc_complaint_table_trainer_complaint_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='doc_complaint_table',
            new_name='complaint_table',
        ),
        migrations.RemoveField(
            model_name='complaint_table',
            name='DOCTOR',
        ),
        migrations.AddField(
            model_name='complaint_table',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MYAPP.login_table'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='trainer_complaint_table',
        ),
    ]
