from django.contrib import admin
from django.urls import path, include

from MYAPP import views


urlpatterns = [
    path('', views.login, name='login'),
    path('login_post', views.login_post, name='login_post'),
    path('log_out', views.log_out, name='log_out'),
    path('admin_home', views.admin_home, name='admin_home'),
    path('admin_dash', views.admin_dash, name='admin_dash'),
    path('viewuser', views.viewuser, name='viewuser'),
    path('viewdoctors', views.viewdoctors, name='viewdoctors'),
    path('doctorverify', views.doctorverify, name='doctorverify'),
    path('viewbookings', views.viewbookings, name='viewbookings'),
    path('viewnotification', views.viewnotification, name='viewnotification'),
    path('viewdoctorbasedreview', views.viewdoctorbasedreview, name='viewdoctorbasedreview'),
    path('Trainers', views.Trainers, name='Trainers'),
    path('Trainer_verify', views.Trainer_verify, name='Trainer_verify'),
    path('changepassword', views.changepassword, name='changepassword'),
    path('viewuser_post', views.viewuser_post, name='viewuser_post'),
    path('doctorverify_search', views.doctorverify_search, name='doctorverify_search'),
    path('admin_doc_search', views.admin_doc_search, name='admin_doc_search'),
    path('search_view_trainer', views.search_view_trainer, name='search_view_trainer'),

    path('admin_accept/<id>', views.admin_accept, name='admin_accept'),
    path('notification', views.notification, name='notification'),
    path('admin_recjected/<id>', views.admin_recjected, name='admin_recjected'),
    path('delete_notification/<nid>', views.delete_notification, name='delete_notification'),
    path('admin_add_noti', views.admin_add_noti, name='admin_add_noti'),
    path('admin_add_noti_post', views.admin_add_noti_post, name='admin_add_noti_post'),
    path('admin_search_noti', views.admin_search_noti, name='admin_search_noti'),
    path('changepassword_POST', views.changepassword_POST, name='changepassword_POST'),
    path('viewdoctorbasedreview', views.viewdoctorbasedreview, name='viewdoctorbasedreview'),
    path('search_doctor', views.search_doctor, name='search_doctor'),
    path('search_trainer', views.search_trainer, name='search_trainer'),
    path('admin_view_complaint', views.admin_view_complaint, name='admin_view_complaint'),
    path('admin_reply_complaint/<id>', views.admin_reply_complaint, name='admin_reply_complaint'),
    path('admin_reply_complaint_post', views.admin_reply_complaint_post, name='admin_reply_complaint_post'),
    path('adm_rejectedyoga/<id>', views.adm_rejectedyoga, name='adm_rejectedyoga'),
    path('adm_acceptyoga/<id>', views.adm_acceptyoga, name='adm_acceptyoga'),

    path('doct_regi', views.doct_regi, name='doct_regi'),
    path('doct_regi_code', views.doct_regi_code, name='doct_regi_code'),
    path('doctor_home', views.doctor_home, name='doctor_home'),
    path('Manage_Schedule', views.Manage_Schedule, name='Manage_Schedule'),
    path('View_Notification', views.View_Notification, name='View_Notification'),
    path('changepassword1', views.changepassword1, name='changepassword1'),
    path('View_Profile', views.View_Profile, name='View_Profile'),
    path('changepassword', views.changepassword, name='changepassword'),
    path('view_review_and_Rating', views.view_review_and_Rating, name='view_review_and_Rating'),
    path('View_Accepted_Booking_p1', views.View_Accepted_Booking_p1, name='View_Accepted_Booking_p1'),
    path('View_Accepted_Booking_p2/<id>', views.View_Accepted_Booking_p2, name='View_Accepted_Booking_p2'),
    path('View_Booking_And_Verify', views.View_Booking_And_Verify, name='View_Booking_And_Verify'),
    path('Schedule', views.Schedule, name='Schedule'),
    path('doc_update', views.doc_update, name='doc_update'),
    path('update_save', views.update_save, name='update_save'),
    path('Schedule_post', views.Schedule_post, name='Schedule_post'),
    path('delete_schedule/<id>', views.delete_schedule, name='delete_schedule'),
    path('changepassword1_POST', views.changepassword1_POST, name='changepassword1_POST'),
    path('doctor_accept/<id>', views.doctor_accept, name='doctor_accept'),
    path('doctor_reject/<id>', views.doctor_reject, name='doctor_reject'),
    path('doc_search', views.doc_search, name='doc_search'),
    path('View_Accepted_Booking_p2_post', views.View_Accepted_Booking_p2_post, name='View_Accepted_Booking_p2_post'),
    path('yoga_regi', views.yoga_regi, name='yoga_regi'),
    path('yoga_regi_code', views.yoga_regi_code, name='yoga_regi_code'),
    path('yoga_home', views.yoga_home, name='yoga_home'),
    path('View_User_request', views.View_User_request, name='View_User_request'),
    path('View_Tips', views.View_Tips, name='View_Tips'),
    path('yoga_videos', views.yoga_videos, name='yoga_videos'),
    path('change_password', views.change_password, name='change_password'),
    path('View_accepted_User_request', views.View_accepted_User_request, name='View_accepted_User_request'),
    path('view_profile', views.view_profile, name='view_profile'),
    path('View_uploaded_videos', views.View_uploaded_videos, name='View_uploaded_videos'),
    path('trainer_accept_user/<id>', views.trainer_accept_user, name='trainer_accept_user'),
    path('trainer_reject_user/<id>', views.trainer_reject_user, name='trainer_reject_user'),
    path('trainer_search_request', views.trainer_search_request, name='trainer_search_request'),
    path('add_Tips', views.add_Tips, name='add_Tips'),
    path('yoga_view_notification', views.yoga_view_notification, name='yoga_view_notification'),
    path('trainer_add_tips_post', views.trainer_add_tips_post, name='trainer_add_tips_post'),
    path('delete_tips/<id>', views.delete_tips, name='delete_tips'),
    path('changepasswordd_POST', views.changepasswordd_POST, name='changepasswordd_POST'),
    path('yoga_video_upl', views.yoga_video_upl, name='yoga_video_upl'),
    path('delete_videos/<id>', views.delete_videos, name='delete_videos'),

    #    -----------------trainerchat user--------------
    path('chatwithuser', views.chatwithuser, name='chatwithuser'),
    path('chatview', views.chatview, name='chatview'),
    path('coun_msg/<int:id>', views.coun_msg, name='coun_msg'),
    path('coun_insert_chat/<str:msg>/<int:id>', views.coun_insert_chat, name='coun_insert_chat'),

    #     -------------------------docchat---------------------------
    path('chatwith_doc', views.chatwith_doc, name='chatwith_doc'),
    path('chat_doc', views.chat_doc, name='chat_doc'),
    path('coun_msg_doc/<int:id>', views.coun_msg_doc, name='coun_msg_doc'),
    path('coun_insert_chat_doc/<str:msg>/<int:id>', views.coun_insert_chat_doc, name='coun_insert_chat_doc'),

    #     ----------flutter-------------------------
    path('and_login', views.and_login, name='and_login'),
    path('and_register', views.and_register, name='and_register'),
    path('and_view_profile', views.and_view_profile, name='and_view_profile'),
    path('and_update_profile', views.and_editprofile, name='and_editprofile'),
    path('user_view_schedules', views.user_view_schedules, name='user_view_schedules'),
    path('user_view_bookings', views.user_view_bookings, name='user_view_bookings'),
    path('book_schedule', views.book_schedule, name='book_schedule'),
    path('user_view_doctor', views.user_view_doctor, name='user_view_doctor'),
    path('doc_profile', views.doc_profile, name='doc_profile'),
    path('fetch_schedule', views.fetch_schedule, name='fetch_schedule'),
    path('user_view_trainers', views.user_view_trainers, name='user_view_trainers'),
    path('trainer_profile', views.trainer_profile, name='trainer_profile'),
    path('user_view_trainer_review', views.user_view_trainer_review, name='user_view_trainer_review'),
    path('user_send_trainer_review', views.user_send_trainer_review, name='user_send_trainer_review'),
    path('user_view_trainer_request', views.user_view_trainer_request, name='user_view_trainer_request'),
    path('user_send_trainer_request', views.user_send_trainer_request, name='user_send_trainer_request'),
    path('user_view_complaint', views.user_view_complaint, name='user_view_complaint'),
    path('user_send_complaint', views.user_send_complaint, name='user_send_complaint'),
    path('user_delete_comlaint', views.user_delete_comlaint, name='user_delete_comlaint'),
    path('user_view_prescription', views.user_view_prescription, name='user_view_prescription'),
    path('user_changepassword', views.user_changepassword, name='user_changepassword'),
    path('user_send_feedback', views.user_send_feedback, name='user_send_feedback'),
    path('user_delete_bookings', views.user_delete_bookings, name='user_delete_bookings'),
    path('user_view_tips', views.user_view_tips, name='user_view_tips'),
    path('user_view_noti', views.user_view_noti, name='user_view_noti'),

    path('user_doc_viewchat', views.user_doc_viewchat, name='user_doc_viewchat'),
    path('user_doc_sendchat', views.user_doc_sendchat, name='user_doc_sendchat'),
    path('user_trainer_viewchat', views.user_trainer_viewchat, name='user_trainer_viewchat'),
    path('user_trainer_sendchat', views.user_trainer_sendchat, name='user_trainer_sendchat'),

    # --------------model------------------
    path('symp2_api', views.symp2_api, name='symp2_api'),
    path('prediction_load_post', views.prediction_load_post, name='prediction_load_post'),

# -------------yoga---------
    path('posture', views.posture, name='posture'),
    path('recom', views.recom, name='recom'),



#     -------------upation---------------
    path('user_send_doctor_complaint',views.user_send_doctor_complaint,name='user_send_doctor_complaint'),
    path('user_view_doc_complaint',views.user_view_doc_complaint,name='user_view_doc_complaint'),
    path('delete_user/<id>',views.delete_user,name='delete_user'),

    path('yoga_profile', views.yoga_profile, name='yoga_profile'),
    path('trainer_update', views.trainer_update, name='trainer_update'),
    path('trainer_update_post', views.trainer_update_post, name='trainer_update_post'),
    path('msg_count', views.msg_count, name='msg_count'),

]
